# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2


formats:
    - epub
    - pdf


build:
    tools:
        python:
            version: 3


python:
    install:
        - method: pip
        - requirements: docs/requirements.txt
        path: .


sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: false