# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2


formats:
    - epub
    - pdf
    - htmlzip


build:
    os: ubuntu-20.04
    tools:
        python: "3"


python:
    install:
        - requirements: requirements.txt


sphinx:
    builder: html
    configuration: conf.py
    path: docs
    fail_on_warning: false