# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2


formats:
    - all


build:
    os: ubuntu-20.04
    tools:
        python: "3"


python:
    install:
        - requirements: requirements.txt


sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: false