# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 5.37.4


formats:
    - epub
    - pdf


build:
    tools:
        python:
            version: 3

python:
    install:
        - requirements: ./requirements.txt
        - method: pip


sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: false