# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2


formats:
    - pdf
#    - htmlzip


build:
    os: ubuntu-20.04
    tools:
        python: "3"


python:
    install:
        - requirements: requirements.txt


sphinx:
    builder: html
    configuration: "documentation RST/conf.py"
    fail_on_warning: true